//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelDeBotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boeking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Boeking()
        {
            this.Kortings = new HashSet<Korting>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime StartDate { get; set; }
        public int AmountOfPersons { get; set; }
        public int HotelId { get; set; }
        public int KamerId { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Kamer Kamer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Korting> Kortings { get; set; }
    }
}
