//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelDeBotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kamer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kamer()
        {
            this.Klant1 = new HashSet<Klant>();
        }
    
        public int Id { get; set; }
        public string Naam { get; set; }
        public int Size { get; set; }
        public string Price { get; set; }
        public string Image { get; set; }
        public int HotelId { get; set; }
        public int KlantId { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Klant Klant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Klant> Klant1 { get; set; }
    }
}
